
import { User, Project, Priority } from './types';

export const INITIAL_USERS: Record<string, User> = {
  'user-1': { id: 'user-1', name: 'Alex Johnson', avatarUrl: 'https://picsum.photos/id/1005/32/32' },
  'user-2': { id: 'user-2', name: 'Maria Garcia', avatarUrl: 'https://picsum.photos/id/1011/32/32' },
  'user-3': { id: 'user-3', name: 'James Smith', avatarUrl: 'https://picsum.photos/id/1025/32/32' },
  'user-4': { id: 'user-4', name: 'Priya Patel', avatarUrl: 'https://picsum.photos/id/1027/32/32' },
};

export const INITIAL_PROJECT_STATE: Project = {
  id: 'proj-1',
  name: 'Q3 Marketing Campaign',
  tasks: {
    'task-1': {
      id: 'task-1',
      title: 'Draft campaign brief',
      description: 'Create the initial campaign brief document outlining goals, target audience, and key messaging.',
      priority: Priority.High,
      startDate: '2024-08-01',
      dueDate: '2024-08-15',
      assigneeIds: ['user-1'],
      tags: ['Planning', 'Content'],
      comments: [
        { id: 'comment-1', userId: 'user-2', text: 'Just a heads up, the target audience definition needs to be more specific. Let\'s discuss tomorrow.', timestamp: new Date(Date.now() - 86400000).toISOString() }
      ],
      subtaskIds: [],
      dependsOn: [],
    },
    'task-2': {
      id: 'task-2',
      title: 'Design social media assets',
      description: 'Develop visuals for Facebook, Instagram, and Twitter. Include 5 different ad variations.',
      priority: Priority.Medium,
      startDate: '2024-08-16',
      dueDate: '2024-08-22',
      assigneeIds: ['user-2'],
      tags: ['Design', 'Social Media'],
      comments: [],
      subtaskIds: [],
      dependsOn: ['task-1'],
    },
    'task-3': {
      id: 'task-3',
      title: 'Develop landing page',
      description: 'Code and deploy the main landing page for the campaign. Ensure it is mobile-responsive.',
      priority: Priority.High,
      startDate: '2024-08-18',
      dueDate: '2024-08-30',
      assigneeIds: ['user-3'],
      tags: ['Development', 'Web'],
      comments: [],
      subtaskIds: ['subtask-1', 'subtask-2'],
      dependsOn: ['task-1'],
    },
     'subtask-1': {
      id: 'subtask-1',
      title: 'LP: HTML Structure',
      description: 'Create the basic HTML structure for the landing page.',
      priority: Priority.High,
      startDate: '2024-08-18',
      dueDate: '2024-08-22',
      assigneeIds: ['user-3'],
      tags: ['Development'],
      comments: [],
      subtaskIds: [],
      dependsOn: [],
      parentId: 'task-3',
    },
    'subtask-2': {
      id: 'subtask-2',
      title: 'LP: CSS Styling',
      description: 'Style the landing page with CSS, ensuring it matches the design mockups.',
      priority: Priority.High,
      startDate: '2024-08-23',
      dueDate: '2024-08-28',
      assigneeIds: ['user-3'],
      tags: ['Development'],
      comments: [],
      subtaskIds: [],
      dependsOn: ['subtask-1'],
      parentId: 'task-3',
    },
    'task-4': {
      id: 'task-4',
      title: 'Set up email marketing sequence',
      description: 'Write copy and configure the 5-part email nurture sequence in Mailchimp.',
      priority: Priority.Medium,
      startDate: '2024-08-20',
      dueDate: '2024-09-05',
      assigneeIds: ['user-4'],
      tags: ['Marketing', 'Email'],
      comments: [],
      subtaskIds: [],
      dependsOn: ['task-1'],
    },
    'task-5': {
      id: 'task-5',
      title: 'Final review with stakeholders',
      description: 'Hold a meeting to get final approval on all assets and plans before launch.',
      priority: Priority.Urgent,
      startDate: '2024-09-08',
      dueDate: '2024-09-10',
      assigneeIds: ['user-1', 'user-4'],
      tags: ['Review', 'Meeting'],
       comments: [
        { id: 'comment-2', userId: 'user-1', text: 'I\'ve scheduled the review meeting for Tuesday at 10 AM. Please confirm your availability.', timestamp: new Date(Date.now() - 172800000).toISOString() }
      ],
      subtaskIds: [],
      dependsOn: ['task-2', 'task-3', 'task-4'],
    },
    'task-6': {
      id: 'task-6',
      title: 'Launch campaign',
      description: 'Go live with all aspects of the campaign.',
      priority: Priority.Urgent,
      startDate: '2024-09-15',
      dueDate: '2024-09-15',
      assigneeIds: ['user-1'],
      tags: ['Launch'],
      comments: [],
      subtaskIds: [],
      dependsOn: ['task-5'],
    },
    'task-7': {
      id: 'task-7',
      title: 'Monitor campaign performance',
      description: 'Track KPIs and gather data for the first-week report.',
      priority: Priority.Medium,
      startDate: '2024-09-16',
      dueDate: '2024-09-22',
      assigneeIds: ['user-4'],
      tags: ['Analytics'],
      comments: [],
      subtaskIds: [],
      dependsOn: ['task-6'],
    },
    'task-8': {
      id: 'task-8',
      title: 'Analyze competitor activity',
      description: 'Research and document what key competitors are doing this quarter.',
      priority: Priority.Low,
      startDate: '2024-08-10',
      dueDate: '2024-08-25',
      assigneeIds: ['user-2'],
      tags: ['Research'],
      comments: [],
      subtaskIds: [],
      dependsOn: [],
    }
  },
  columns: {
    'col-1': { id: 'col-1', title: 'To Do', taskIds: ['task-1', 'task-8', 'subtask-1'] },
    'col-2': { id: 'col-2', title: 'In Progress', taskIds: ['task-2', 'task-3', 'subtask-2'] },
    'col-3': { id: 'col-3', title: 'In Review', taskIds: ['task-4'] },
    'col-4': { id: 'col-4', title: 'Done', taskIds: ['task-5', 'task-6', 'task-7'] },
  },
  columnOrder: ['col-1', 'col-2', 'col-3', 'col-4'],
};